# Generated by Django 2.0.3 on 2018-03-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to Move'), ('S', 'Second player to Move'), ('W', 'First player Wins'), ('L', 'Second player Wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
